language: go

os: [linux, osx]

osx_image: mavericks

before_install:
    - echo $GOPATH
    - echo $GOROOT
    - mkdir -p /home/travis/gopath/src/github.com/oliveagle/go-collectors
    - git clone https://github.com/oliveagle/go-collectors.git /home/travis/gopath/src/github.com/oliveagle/go-collectors
    - git clone https://github.com/bosun-monitor/bosun.git /home/travis/gopath/src/bosun.org

install:
    - go get -u github.com/tools/godep
    - sudo apt-get install tree

script:
   - tree -d /home/travis/gopath
   - cd /home/travis/gopath/src/github.com/oliveagle/go-collectors/collectors
   - pwd
   - godep go test .
