language: go

os: [linux, osx]

osx_image: mavericks

before_install:
    - echo $GOPATH
    - echo $GOROOT
    - sudo apt-get install tree
    # currently, bosun.org is still needed. coz it's _third_party cannot managed by godep
    - git clone https://github.com/bosun-monitor/bosun.git /home/travis/gopath/src/bosun.org

install:
    - go get -u github.com/tools/godep

script:
   #  debug gopath
   - tree -d /home/travis/gopath
   - tree -L 1 /proc 
   - cd /home/travis/gopath/src/github.com/oliveagle/go-collectors/collectors
   # test script
   - godep go test .
